version: '3.7'
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=advisor
      - POSTGRES_PASSWORD=advisor
      - POSTGRES_DB=advisor
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres_data:
