version: "3.7"
services:
  db:
    image: postgres:15.1
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build: ./backend
    container_name: api
    environment: &api-environment
      DJANGO_ENV: dev
      DJANGO_SECRET_KEY: change-me
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - static_data:/usr/src/app/static/
      - media_data:/usr/src/app/media/

  bot:
    build: ./bot
    container_name: bot
    env_file:
      - ".env"
    command: python main.py
    volumes:
      - ./bot:/usr/src/advisor/
    restart: always
    depends_on:
      - api

volumes:
  postgres_data:
  static_data:
  media_data:
